# Generated by Django 5.0 on 2024-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=26)),
                ('Email', models.EmailField(max_length=254)),
                ('Sunjects', models.CharField(max_length=50)),
                ('Message', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
