# Generated by Django 5.0 on 2024-03-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
    ]
