# Generated by Django 5.0 on 2024-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_customer_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Course',
        ),
        migrations.AddField(
            model_name='customer',
            name='Course',
            field=models.ManyToManyField(to='web.course'),
        ),
    ]
