# Generated by Django 5.0 on 2024-03-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_customer_course_customer_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Course',
        ),
        migrations.AddField(
            model_name='customer',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course'),
        ),
    ]
