# Generated by Django 5.0 on 2024-03-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_customer_course_customer_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursed', to='web.course'),
        ),
    ]
