# Generated by Django 5.0 on 2024-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_customer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checks',
            field=models.BooleanField(default=True),
        ),
    ]
