# Generated by Django 5.0 on 2024-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_customer_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
