# Generated by Django 5.0 on 2024-03-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_customer_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='checks',
        ),
    ]
