# Generated by Django 5.0 on 2024-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_customer_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pro',
            field=models.BooleanField(default=True),
        ),
    ]
