# Generated by Django 5.0 on 2024-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_customer_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
