# Generated by Django 5.0 on 2024-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
