# Generated by Django 5.0 on 2024-03-31 19:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_about_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grammer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
