# Generated by Django 5.0 on 2024-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, default='catagorey/pexels-christina-morillo-1181676.jpg', null=True, upload_to='catagorey'),
        ),
    ]
