# Generated by Django 5.0 on 2024-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_catagory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(default='video/Saras_Day_-_featuring_the_Present_Simple.mkv', upload_to='video/'),
        ),
    ]
