# Generated by Django 5.0 on 2024-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course/7.jpg', null=True, upload_to='course/'),
        ),
    ]
